import Config

# Configure your database.
# POSTGRES_HOST / POSTGRES_USER / POSTGRES_PASSWORD / POSTGRES_DB are read from
# env vars so the same dev.exs works both locally and inside Docker Compose.
config :ad_butler, AdButler.Repo,
  username: System.get_env("POSTGRES_USER", "postgres"),
  password: System.get_env("POSTGRES_PASSWORD", "postgres"),
  hostname: System.get_env("POSTGRES_HOST", "localhost"),
  database: System.get_env("POSTGRES_DB", "ad_butler_dev"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Bind to loopback by default; set PHX_BIND=0.0.0.0 (e.g. in Docker Compose)
# to accept connections from outside the container.
bind_ip =
  case System.get_env("PHX_BIND", "127.0.0.1") do
    "0.0.0.0" -> {0, 0, 0, 0}
    _ -> {127, 0, 0, 1}
  end

config :ad_butler, AdButlerWeb.Endpoint,
  http: [ip: bind_ip],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "22xoMC5Pk5W0Y/A/OiDmQWx6UE5xaeloGTFbn7mtl+DVTUMwJ2cfoH2IQ0a7HxJ4",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ad_butler, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ad_butler, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :ad_butler, AdButlerWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/ad_butler_web/router\.ex$",
      ~r"lib/ad_butler_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ad_butler, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :ad_butler, :rabbitmq,
  url: System.get_env("RABBITMQ_URL", "amqp://guest:guest@localhost"),
  pool_size: 5

config :ad_butler, session_secure_cookie: false

# Placeholder Meta credentials — only needed if you want to test the real OAuth
# flow in dev. The /dev/login bypass works without these.
config :ad_butler,
  meta_app_id: System.get_env("META_APP_ID", "dev_meta_app_id"),
  meta_app_secret: System.get_env("META_APP_SECRET", "dev_meta_app_secret"),
  meta_oauth_callback_url:
    System.get_env("META_OAUTH_CALLBACK_URL", "http://localhost:4000/auth/meta/callback")

config :ad_butler,
  session_signing_salt: "dev_signing_salt",
  session_encryption_salt: "dev_encrypt_salt"

config :ad_butler, AdButlerWeb.Endpoint, live_view: [signing_salt: "dev_lv_salt"]

cloak_key_dev =
  Base.decode64!(
    System.get_env(
      "CLOAK_KEY_DEV",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
    )
  )

if byte_size(cloak_key_dev) != 32 do
  raise "CLOAK_KEY_DEV must decode to exactly 32 bytes"
end

config :ad_butler, AdButler.Vault,
  ciphers: [
    default: {Cloak.Ciphers.AES.GCM, tag: "AES.GCM.V1", key: cloak_key_dev}
  ]
