import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ad_butler, AdButlerWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Session and LiveView salts — rotate these when compromised (clears active sessions).
# The values below were generated with `mix phx.gen.secret` and are unique to production.
config :ad_butler,
  session_signing_salt: "dCPITWsx",
  session_encryption_salt: "p6is6RY14gxjc17W"

config :ad_butler, AdButlerWeb.Endpoint, live_view: [signing_salt: "RdNeLY9O"]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
