defmodule AdButler.Embeddings do
  @moduledoc """
  Context for stored embedding vectors backed by `pgvector`.

  Embeddings are not tenant-scoped at this layer — they reference source rows
  (ads, findings, help-doc chunks) via `ref_id`. Callers exposing similarity
  results to user-facing surfaces MUST compose the full chain:

      kind
      |> Embeddings.nearest(query_vector, limit)
      |> case do
        {:ok, rows} ->
          rows
          |> Embeddings.tenant_filter_results(user)
          |> Embeddings.scrub_for_user()
      end

  `tenant_filter_results/2` drops cross-tenant `ref_id`s; `scrub_for_user/1`
  nils `content_excerpt` for ad/finding kinds (advertiser-typed PII risk —
  see `Embedding.@moduledoc`). Skipping either step is a leak.

  HNSW index (`embedding vector_cosine_ops`, `m=16, ef_construction=64`) is
  the active ANN structure (D0011); cosine distance is the canonical metric.
  """

  import Ecto.Query

  alias AdButler.Accounts.User
  alias AdButler.Ads
  alias AdButler.Analytics
  alias AdButler.Embeddings.Embedding
  alias AdButler.Repo

  @doc """
  Returns the SHA-256 hex digest of `text`. Stored as `content_hash` on the
  embedding row so the refresh worker can short-circuit on unchanged source.
  """
  @spec hash_content(String.t()) :: String.t()
  def hash_content(text) when is_binary(text) do
    :crypto.hash(:sha256, text) |> Base.encode16(case: :lower)
  end

  @doc """
  Upserts an embedding row keyed on `(kind, ref_id)`. Returns
  `{:ok, embedding}` on success or `{:error, changeset}` on validation failure.

  When a row already exists for `(kind, ref_id)`, the embedding vector,
  content_hash, content_excerpt, metadata, and `updated_at` are replaced.
  Caller is expected to compute `content_hash` ahead of time (use
  `hash_content/1`) so the refresh worker can compare hashes without re-reading
  this row.
  """
  @spec upsert(map()) :: {:ok, Embedding.t()} | {:error, Ecto.Changeset.t()}
  def upsert(attrs) do
    %Embedding{}
    |> Embedding.changeset(attrs)
    |> Repo.insert(
      on_conflict:
        {:replace, [:embedding, :content_hash, :content_excerpt, :metadata, :updated_at]},
      conflict_target: [:kind, :ref_id],
      # `returning: true` so a conflict-update returns the existing row's id
      # rather than the autogenerated one from the changeset.
      returning: true
    )
  end

  @doc """
  Bulk-upserts a list of embedding row maps in a single `Repo.insert_all/3`,
  keyed on `(kind, ref_id)`. Returns `{:ok, count}` where `count` is the
  number of rows affected — callers should compare against `length(rows)` to
  detect partial writes.

  Caller-supplied row shape: `:kind`, `:ref_id`, `:embedding`, `:content_hash`
  required; `:content_excerpt` and `:metadata` optional. `:inserted_at` and
  `:updated_at` are populated here.

  Bypasses `Embedding.changeset/2` validations — `Repo.insert_all/3` runs no
  changesets. The DB CHECK enforces `kind`; `content_hash` is trusted because
  the only producer is `hash_content/1` (deterministic 64-char hex). Use
  `upsert/1` for single-row writes that should run validations.
  """
  @spec bulk_upsert([map()]) :: {:ok, non_neg_integer()}
  def bulk_upsert([]), do: {:ok, 0}

  def bulk_upsert(rows) when is_list(rows) do
    now = DateTime.utc_now()
    rows_with_timestamps = Enum.map(rows, &Map.merge(%{inserted_at: now, updated_at: now}, &1))

    {count, _} =
      Repo.insert_all(
        Embedding,
        rows_with_timestamps,
        on_conflict:
          {:replace, [:embedding, :content_hash, :content_excerpt, :metadata, :updated_at]},
        conflict_target: [:kind, :ref_id]
      )

    {:ok, count}
  end

  @doc """
  Returns the `limit` nearest embedding rows of the given `kind` to
  `query_vector`, ordered ascending by cosine distance (closest first).

  `kind` must be one of `Embedding.kinds/0`. `limit` is clamped to
  `#{50}` to keep the kNN scan bounded — Week-9 chat tools should not request
  more than this in one shot.

  `query_vector` may be a list of floats, a `Pgvector.Vector` struct, or any
  value `Pgvector.Ecto.Vector` can dump. Empty input returns `{:ok, []}`.

  Returns `{:error, {:invalid_kind, kind}}` when `kind` is a binary outside
  `Embedding.kinds/0`. Non-binary `kind` raises `FunctionClauseError`.

  This function returns raw cross-tenant rows. Compose with
  `tenant_filter_results/2` and `scrub_for_user/1` before exposing the
  result to a user-facing surface — see this module's `@moduledoc`.

  TODO: when any single kind exceeds ~50k rows, switch the HNSW index to
  per-kind partial indexes (`WHERE kind = 'ad'`, etc.) — recall on a
  multi-kind table degrades fast as the index grows.
  """
  @valid_kinds Embedding.kinds()
  @max_nearest_limit 50

  @spec nearest(String.t(), Pgvector.Vector.t() | [float()], pos_integer()) ::
          {:ok, [Embedding.t()]} | {:error, {:invalid_kind, String.t()}}
  def nearest(kind, query_vector, limit)
      when is_binary(kind) and kind in @valid_kinds and is_integer(limit) and limit > 0 do
    pg_vector = Pgvector.new(query_vector)
    capped = min(limit, @max_nearest_limit)

    rows =
      Repo.all(
        from e in Embedding,
          where: e.kind == ^kind,
          order_by: fragment("? <=> ?", e.embedding, ^pg_vector),
          limit: ^capped
      )

    {:ok, rows}
  end

  def nearest(kind, _query_vector, _limit) when is_binary(kind) do
    {:error, {:invalid_kind, kind}}
  end

  @doc """
  Returns a map of `ref_id => content_hash` for every embedding row of the
  given kind. Used by the refresh worker to skip rows whose source content
  has not changed since the last embedding.

  Returns `{:error, {:invalid_kind, kind}}` when `kind` is not in
  `Embedding.kinds/0`.
  """
  @spec list_ref_id_hashes(String.t()) ::
          {:ok, %{binary() => String.t()}} | {:error, {:invalid_kind, String.t()}}
  def list_ref_id_hashes(kind) when is_binary(kind) and kind in @valid_kinds do
    map =
      Repo.all(
        from e in Embedding,
          where: e.kind == ^kind,
          select: {e.ref_id, e.content_hash}
      )
      |> Map.new()

    {:ok, map}
  end

  def list_ref_id_hashes(kind) when is_binary(kind) do
    {:error, {:invalid_kind, kind}}
  end

  @doc """
  Filters a list of `Embedding` rows down to those whose `ref_id` is owned by
  `user`. Per-kind logic:

    * `kind == "doc_chunk"` — pass-through (admin-curated, global).
    * `kind == "ad"` — kept iff `ref_id` belongs to one of `user`'s ads.
    * `kind == "finding"` — kept iff `ref_id` belongs to one of `user`'s
      findings.

  Use this on the result of `nearest/3` BEFORE exposing rows to a user-facing
  surface (chat tools, similarity widgets). Skipping this step is a tenant
  leak — embeddings are stored cross-tenant by design.

  TODO: when `Chat` context lands (Week 9), migrate this helper there since
  `Embeddings` doesn't naturally own user-facing tenant filtering.
  """
  @spec tenant_filter_results([Embedding.t()], User.t()) :: [Embedding.t()]
  def tenant_filter_results(rows, %User{} = user) when is_list(rows) do
    {ad_rows, rest} = Enum.split_with(rows, &(&1.kind == "ad"))
    {finding_rows, rest} = Enum.split_with(rest, &(&1.kind == "finding"))
    # safe: doc_chunk is admin-curated only — see lib/mix/tasks/ad_butler.seed_help_docs.ex
    {doc_rows, unknown_rows} = Enum.split_with(rest, &(&1.kind == "doc_chunk"))

    if unknown_rows != [] do
      raise "Embeddings.tenant_filter_results/2: refusing to filter unknown kinds " <>
              inspect(Enum.map(unknown_rows, & &1.kind) |> Enum.uniq()) <>
              " — fail-closed to avoid cross-tenant leak. Add explicit handling."
    end

    kept_ads = filter_by_ownership(ad_rows, fn -> Ads.list_ad_ids_for_user(user) end)

    kept_findings =
      filter_by_ownership(finding_rows, fn -> Analytics.list_finding_ids_for_user(user) end)

    kept_ads ++ kept_findings ++ doc_rows
  end

  defp filter_by_ownership([], _id_fun), do: []

  defp filter_by_ownership(rows, id_fun) do
    owned = id_fun.() |> MapSet.new()
    Enum.filter(rows, &MapSet.member?(owned, &1.ref_id))
  end

  @doc """
  Returns `rows` with `content_excerpt` set to `nil` for every row whose
  `kind` is NOT `"doc_chunk"`. Use immediately before rendering similarity
  results to user-facing surfaces — `content_excerpt` for ad/finding kinds
  may carry advertiser-typed PII (see `Embedding.@moduledoc`).

  Idempotent. Caller composition: `nearest/3 |> tenant_filter_results/2 |> scrub_for_user/1`.
  """
  @spec scrub_for_user([Embedding.t()]) :: [Embedding.t()]
  def scrub_for_user(rows) when is_list(rows) do
    Enum.map(rows, fn
      %Embedding{kind: "doc_chunk"} = row -> row
      %Embedding{} = row -> %{row | content_excerpt: nil}
    end)
  end
end
