defmodule AdButlerWeb.Endpoint do
  @moduledoc """
  Phoenix endpoint for AdButlerWeb.

  Configures static file serving, LiveView socket, session management, and the
  plug pipeline. Session salts are read from `Application` env on every request
  (`fetch_env!`) so runtime config updates take effect without a restart. See
  inline comments for the distinction between `@session_options` (compile-time,
  used only by LiveView connect_info) and the `session/2` plug (runtime).
  """

  use Phoenix.Endpoint, otp_app: :ad_butler

  # @session_options is frozen at compile time (compile_env!) and used only for the
  # LiveView socket connect_info macro. Salt values set in runtime.exs are NOT picked
  # up here without a full recompile. Rotating these salts requires recompile + restart.
  # HTTP sessions use the session/2 function plug below, which reads Application env on
  # every request via fetch_env!, so runtime env updates (e.g. hot config reload) take
  # effect immediately — no restart needed. Either way, rotation invalidates all sessions.
  @session_options [
    store: :cookie,
    key: "_ad_butler_key",
    signing_salt: Application.compile_env!(:ad_butler, :session_signing_salt),
    encryption_salt: Application.compile_env!(:ad_butler, :session_encryption_salt),
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:ad_butler, :session_secure_cookie, true)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ad_butler,
    gzip: not code_reloading?,
    only: AdButlerWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ad_butler
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :session
  plug AdButlerWeb.Router

  # Reads session salts from Application env on every request (fetch_env!), so salt
  # updates applied at runtime (e.g. via hot config reload) take effect immediately
  # without a restart. fetch_env! raises on the first request if a key is missing,
  # surfacing misconfiguration immediately rather than silently using defaults.
  defp session(conn, _opts) do
    opts =
      Plug.Session.init(
        store: :cookie,
        key: "_ad_butler_key",
        signing_salt: Application.fetch_env!(:ad_butler, :session_signing_salt),
        encryption_salt: Application.fetch_env!(:ad_butler, :session_encryption_salt),
        same_site: "Lax",
        http_only: true,
        secure: Application.get_env(:ad_butler, :session_secure_cookie, true)
      )

    Plug.Session.call(conn, opts)
  end
end
