defmodule AdButlerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ad_butler

  # @session_options is baked in at compile time and used only for the LiveView socket
  # connect_info macro. Rotating salts here requires a full recompile and restart.
  # HTTP sessions use the session/2 function plug below, which reads Application env at
  # request time and can pick up salt changes without recompiling (restart only).
  # Either way, rotation invalidates all active sessions.
  @session_options [
    store: :cookie,
    key: "_ad_butler_key",
    signing_salt: Application.compile_env!(:ad_butler, :session_signing_salt),
    encryption_salt: Application.compile_env!(:ad_butler, :session_encryption_salt),
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:ad_butler, :session_secure_cookie, true)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ad_butler,
    gzip: not code_reloading?,
    only: AdButlerWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ad_butler
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :session
  plug AdButlerWeb.Router

  # Reads session salts from Application env at call time rather than a frozen module
  # attribute. This allows salt updates to take effect without a full restart in
  # scenarios where the Application env is updated externally (e.g., hot config reload).
  # fetch_env! raises on the first request if a key is missing; misconfiguration
  # surfaces immediately on the first HTTP hit rather than silently using defaults.
  defp session(conn, _opts) do
    opts =
      Plug.Session.init(
        store: :cookie,
        key: "_ad_butler_key",
        signing_salt: Application.fetch_env!(:ad_butler, :session_signing_salt),
        encryption_salt: Application.fetch_env!(:ad_butler, :session_encryption_salt),
        same_site: "Lax",
        http_only: true,
        secure: Application.get_env(:ad_butler, :session_secure_cookie, true)
      )

    Plug.Session.call(conn, opts)
  end
end
